# POD setup for react-app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-depl
spec:
  selector:
    matchLabels:
      app: react-app
  replicas: 1
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: vishalsg42/react-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
# Service setup for react-app
apiVersion: v1
kind: Service
metadata:
  name: react-app-srv
# spec:
#   type: NodePort
#   selector:
#     app: react-app
#   ports:
#     - name: react-app
#       protocol: TCP
#       port: 3000
#       targetPort: 3000
spec:
  type: LoadBalancer
  selector:
    app: react-app
  ports:
    - name: react-app
      protocol: TCP
      port: 3000
      targetPort: 3000
